Cache PIN in Linux keyring
str4d/age-plugin-yubikey pull request #168
Opened 2024-02-18 20:39 UTC by Ma27

Unresolved questions:
* [ ] should the timeout be configurable? If so, how?
* [ ] check if it builds on non-Linux.
* [ ] a more elegant way to handle the LInux-only code?
* [ ] perhaps we want to make this opt-in?

I'm happy to update the docs accordingly when we agreed on whether this is desirable.

cc @lheckemann

2024-03-23 13:32 UTC, Ma27 commented
Pushed another commit which sets the PIN while creating the key and sets the timeout after that. Unfortunately, `key_update` discards the timeout, so that's the only way to have expiring keys.

Btw cc @str4d, opinions? :)

2024-03-28 18:55 UTC, str4d requested changes
I'm sympathetic to the UX issue, and I am not entirely against this change, but I would want to see documentation about how the Linux keyring behaves when used in this way (and if that behaviour is not consistent across all Linux OSs, an examination of those differences) before this could be merged.

`PinPolicy::Once` means slightly different things to different audiences:
- To users, it means "once per time that the YubiKey is plugged in". The UX expectation is that the user plugs in their YubiKey, types in the PIN once, and then they don't need to do so again before they unplug their YubiKey. Unplugging and plugging in again requires another PIN entry.
- To the YubiKey, it means "once per time that the PIV applet is opened on the YubiKey"; switching to the GPG or CTAP applets cause the PIV applet to be closed and the cached PIN dropped.

The discrepancy between these two meanings causes problems for the users' mental model, and I can see the benefit of using a temporary PIN cache to paper over the user's other apps accessing different YubiKey applets (e.g. for SSH authentication or GPG signing). However, we then need a way to ensure that the keyring cache is cleared when the YubiKey unplugs - and that can occur after `age-plugin-yubikey` has finished running! I don't know what kind of flexibility the Linux keyring offers, but if all we have access to is a timeout, then I don't think this PR is suitable as-is. We'd instead need some way for `age-plugin-yubikey` to spawn an independent child process that manages that keyring caching, and ensures eviction at the right time.

2024-03-28 18:55 UTC, str4d commented on src/key.rs
> +                    if self.yubikey.verify_pin(&cached_pin).is_ok() {
Any PIN caching _MUST_ respect the configured policy for the slot. If the slot uses `PinPolicy::Always`, then we must request the PIN directly from the user, and never cache it. What that means in practice is that the only time this cache should be used is `PinPolicy::Once`.

2024-03-28 18:55 UTC, str4d commented on src/key.rs
> +                    key.set_timeout(300).map_err(|e| format!("set_timeout(300): {e}"))?;
- How reliable is this timeout?
- Given that you are not setting a timeout at the point where the PIN is added to the keyring (I presume due to limitations with the `linux-keyutils` API), this means that if the keyring addition succeeds and then the timeout-setting fails, the PIN is now (IIUC) permanently stored in the keyring (which is not acceptable behaviour).

2024-03-30 13:43 UTC, Ma27 commented
Hi!

FIrst of all, thanks a lot for your input!

> but I would want to see documentation about how the Linux keyring behaves when used in this way (and if that behaviour is not consistent across all Linux OSs, an examination of those differences) before this could be merged.

:+1: will be added to the list above.

Not sure if you've seen the back-and-forth here, after the last iteration I'm not sure if UserSession or Session is what I want, so more research will be necessary anyways.

> However, we then need a way to ensure that the keyring cache is cleared when the YubiKey unplugs - and that can occur after age-plugin-yubikey has finished running!

This is a good point. One thing I did so far was to invalidate the keyring when I lock my machine and I wanted to see if I can do it reasonably with udev as well.

Not sure about the capabilities of the keyring itself, but perhaps some kind of udev rule that will be installed with this package may be an option as well? I'm using a distro-provided package though, not sure how this behaves with `cargo install` yet.

> Any PIN caching MUST respect the configured policy for the slot. If the slot uses PinPolicy::Always, then we must request the PIN directly from the user, and never cache it. What that means in practice is that the only time this cache should be used is PinPolicy::Once.

Agreed :+1: 

> Given that you are not setting a timeout at the point where the PIN is added to the keyring (I presume due to limitations with the linux-keyutils API), this means that if the keyring addition succeeds and then the timeout-setting fails, the PIN is now (IIUC) permanently stored in the keyring (which is not acceptable behaviour).

@lheckemann heh, and I were discussing exactly that!

I reversed that however after finding out that you'll lose the timeout when `keyctl update`ing an entry (https://github.com/torvalds/linux/blob/v6.8/security/keys/key.c#L1083).
See also https://lore.kernel.org/keyrings/ygar0hbrm05.fsf@localhost/T/#m5a684396fdd57947f072809040976f33fff68f8a.
I'd like to understand first why it's implemented that way, but I don't see a reason so far to retain the timeout. We'll need to disable the feature then for kernels w/o this patch.

2025-09-08 12:52 UTC, Ma27 commented
Considering that I'm (1) pretty disappointed by the kernel keyring to not get stuff right such as initializing a key with an expiry and (2) the fact that https://github.com/go-piv/piv-go/pull/182 seems to resolve the race between age-plugin-yubikey and yubikey-agent by not using shared locks anywhere anymore, there's a better solution on the horizon and I'm going to close this.

Nontheless, thanks for your feedback @str4d!

2025-09-08 12:52 UTC, closed without merging